# Generated by Django 5.0.6 on 2024-06-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='title',
        ),
        migrations.AddField(
            model_name='course',
            name='logo',
            field=models.ImageField(blank=True, upload_to='course_logos/'),
        ),
        migrations.AddField(
            model_name='course',
            name='path',
            field=models.CharField(default='default/path/', max_length=200),
        ),
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='course_thumbnails/'),
        ),
        migrations.AddField(
            model_name='lab',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='lab_thumbnails/'),
        ),
        migrations.AddField(
            model_name='path',
            name='cover',
            field=models.ImageField(blank=True, upload_to='path_covers/'),
        ),
        migrations.AddField(
            model_name='path',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='path_thumbnails/'),
        ),
        migrations.DeleteModel(
            name='PathCourse',
        ),
    ]
