# Generated by Django 5.0.6 on 2024-06-17 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htr', '0002_remove_course_title_course_logo_course_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='title',
            field=models.CharField(default='Default Title', max_length=100),
        ),
    ]
