# Generated by Django 5.0.6 on 2024-06-23 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htr', '0003_course_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='htr.path'),
        ),
    ]
