# Generated by Django 5.0.6 on 2024-06-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htr', '0004_alter_course_path'),
    ]


    operations = [
        migrations.AddField(
            model_name='path',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
