# Generated by Django 5.0.6 on 2024-06-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htr', '0005_path_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='logo',
            field=models.ImageField(blank=True, upload_to='path_logos/'),
        ),
    ]
