# Generated by Django 5.0.6 on 2024-06-26 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htr', '0006_path_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='banner_color_end',
            field=models.CharField(default='indigo', max_length=20),
        ),
        migrations.AddField(
            model_name='path',
            name='banner_color_start',
            field=models.CharField(default='blue', max_length=20),
        ),
        migrations.AddField(
            model_name='path',
            name='banner_image',
            field=models.ImageField(blank=True, upload_to='path_banners/'),
        ),
    ]
