# Generated by Django 5.0.6 on 2024-06-26 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('htr', '0007_path_banner_color_end_path_banner_color_start_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='path',
            name='banner_image',
        ),
    ]
