# Generated by Django 5.0.6 on 2024-07-02 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htr', '0008_remove_path_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
