# Generated by Django 5.0.6 on 2024-07-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htr', '0010_remove_lab_lesson_section_question_lab_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='banner_color_end',
            field=models.CharField(default='indigo', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='banner_color_start',
            field=models.CharField(default='blue', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='cover',
            field=models.ImageField(blank=True, upload_to='course_covers/'),
        ),
    ]
