# Generated by Django 5.0.6 on 2024-07-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htr', '0011_course_banner_color_end_course_banner_color_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='hint',
            field=models.TextField(blank=True, null=True),
        ),
    ]
